from pathlib import Path

# read configfile params
LOCAL_CONFIG   = config["entanglement"]

# define variables
INPUT_NODES    = LOCAL_CONFIG["input_nodes"]
DATA_DIR       = Path(config["data_dir"])
WORK_DIR       = Path(workflow.basedir)
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_SUFFIX  = LOCAL_CONFIG["output_suffix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
AF2_DATA       = DATA_DIR / LOCAL_CONFIG["AF2_data"]
EXP_DATA       = DATA_DIR / LOCAL_CONFIG["exp_data"]

# overall goal
rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

# integrate entanglement information from AF2 and experimental structures
rule integrate_entanglements:
    input:
        input_nodes = INPUT_NODES
    conda:
        "env/entanglement.yml"
    params:
        output_dir    = str(OUTPUT_DIR),
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX,
        output_suffix = OUTPUT_SUFFIX,
        AF2_data      = str(AF2_DATA),
        exp_data      = str(EXP_DATA)
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/integrate-entanglement.py \
        --input_nodes    {{input.input_nodes}}    \
        --output_dir     {{params.output_dir}}    \
        --organism_tag   {{params.organism_tag}}  \
        --output_prefix  {{params.output_prefix}} \
        --output_suffix  {{params.output_suffix}} \
        --AF2_data       {{params.AF2_data}}      \
        --exp_data       {{params.exp_data}}
        """
