from pathlib import Path

LOCAL_CONFIG  = config["Rosetta_scoring"]

INPUT_NODES   = Path(LOCAL_CONFIG["input_nodes"])
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = config["output_suffix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
SCORE_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"] / "scores"
ORGANISM_TAG  = config["organism_label"]
NPROCS        = LOCAL_CONFIG["nprocessors"]
RELAX_EXEC    = LOCAL_CONFIG["relax_executable"]
NSTRUC        = LOCAL_CONFIG["n_structures"]

rule all:
    input:
        str(SCORE_DIR / ".all_scores_done"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl")

rule run_Rosetta:
    input:
        INPUT_NODES
    conda:
        "env/run-Rosetta.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = SCORE_DIR,
        organism_tag   = ORGANISM_TAG,
        nprocessors    = NPROCS,
        relax_exec     = RELAX_EXEC,
        nstruc         = NSTRUC
    output:
        str(SCORE_DIR / ".all_scores_done")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/run-Rosetta.py \
        --nodes            {{input}} \
        --output_dir       {{params.output_dir}} \
        --output_prefix    {{params.output_prefix}} \
        --organism_tag     {{params.organism_tag}} \
        --nprocessors      {{params.nprocessors}} \
        --relax_executable {{params.relax_exec}} \
        --nstruc           {{params.nstruc}}
        """

rule add_scores_to_nodes:
    input:
        input_nodes       = INPUT_NODES,
        input_done_signal = str(SCORE_DIR / ".all_scores_done")
    conda:
        "env/run-Rosetta.yml"
    params:
        output_prefix = OUTPUT_PREFIX,
        output_suffix = OUTPUT_SUFFIX,
        input_dir     = SCORE_DIR,
        organism_tag  = ORGANISM_TAG,
        output_dir    = OUTPUT_DIR,
        nstruc        = NSTRUC
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-Rosetta-scores.py \
        --nodes         {{input.input_nodes}} \
        --input_dir     {{params.input_dir}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --organism_tag  {{params.organism_tag}} \
        --nstruc        {{params.nstruc}}
        """
