from pathlib import Path

LOCAL_CONFIG   = config["domain_annotations"]

DATA_DIR1      = Path(LOCAL_CONFIG["input_dir"])
DATA_DIR2      = Path(config["data_dir"])
WORK_DIR       = Path(workflow.basedir)
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
DOMAIN_DATA    = DATA_DIR2 / LOCAL_CONFIG["annotations"]

rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2-LiPMS-entanglement-chaperones-oligomers-domains.pkl"

rule extract_domain_info:
    input:
        nodes = f"{DATA_DIR1}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2-LiPMS-entanglement-chaperones-oligomers.pkl"
    conda:
        "env/domains.yml"
    params:
        output_dir    = OUTPUT_DIR,  
        organism_tag  = ORGANISM_TAG, 
        output_prefix = OUTPUT_PREFIX,
        domain_data   = str(DOMAIN_DATA)
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/extract-InterPro.py \
        --output_dir     {{params.output_dir}}               \
        --output_prefix  {{params.output_prefix}}            \
        --organism_tag   {{params.organism_tag}}             \
        --domain_data    {{params.domain_data}}              \
        --nodes          {{input.nodes}}
        """

rule process_domain_info:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations.csv"
    conda:
        "env/domains.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-InterPro.py \
        --output_dir     {{params.output_dir}}               \
        --output_prefix  {{params.output_prefix}}            \
        --organism_tag   {{params.organism_tag}}             \
        --input_data     {{input}}
        """

rule add_domain_info:
    input:
        nodes = f"{DATA_DIR1}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2-LiPMS-entanglement-chaperones-oligomers.pkl",
        info  = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.pkl"
    conda:
        "env/domains.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2-LiPMS-entanglement-chaperones-oligomers-domains.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-InterPro.py \
        --output_dir     {{params.output_dir}}           \
        --output_prefix  {{params.output_prefix}}        \
        --organism_tag   {{params.organism_tag}}         \
        --domain_data    {{input.info}}                  \
        --input_nodes    {{input.nodes}}
        """
