from pathlib import Path

# read configfile params
LOCAL_CONFIG   = config["oligomer"]

# define variables
INPUT_NODES    = LOCAL_CONFIG["input_nodes"]
DATA_DIR       = Path(config["data_dir"])
WORK_DIR       = Path(workflow.basedir)
OUTPUT_SUFFIX  = LOCAL_CONFIG["output_suffix"]
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
OLIG_DATA      = DATA_DIR / LOCAL_CONFIG["oligomer_data"]
ID_MAP_FILE    = DATA_DIR / config["sequence_parsing"]["map_file"]

# overall goal
rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-oligomers-per-node.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

# parse Complex Portal information
rule parse_oligomer_info:
    input:
        nodes = INPUT_NODES
    conda:
        "env/oligomers.yml"
    params:
        output_dir    = OUTPUT_DIR,  
        organism_tag  = ORGANISM_TAG, 
        output_prefix = OUTPUT_PREFIX,
        oligomer_data = OLIG_DATA,
        map_file      = ID_MAP_FILE
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-oligomers-per-node.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-oligomers.py \
        --output_dir     {{params.output_dir}}                \
        --output_prefix  {{params.output_prefix}}             \
        --organism_tag   {{params.organism_tag}}              \
        --oligomer_data  {{params.oligomer_data}}             \
        --map_file       {{params.map_file}}                  \
        --nodes          {{input.nodes}}
        """

# add oligomerization state information to pd.DataFrame
rule add_oligomer_info:
    input:
        input_nodes = INPUT_NODES,
        input_oligs = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-oligomers-per-node.csv"
    conda:
        "env/oligomers.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX,
        output_suffix = OUTPUT_SUFFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-oligomers.py \
        --input_nodes    {{input.input_nodes}}            \
        --output_dir     {{params.output_dir}}            \
        --output_prefix  {{params.output_prefix}}         \
        --output_suffix  {{params.output_suffix}}         \
        --organism_tag   {{params.organism_tag}}          \
        --olig_data      {{input.input_oligs}}            \
        """
