from pathlib import Path

LOCAL_CONFIG  = config["sequence_parsing"]

WORK_DIR      = Path(workflow.basedir)
DATA_DIR1     = Path(LOCAL_CONFIG["input_dir"])
DATA_DIR2     = Path(config["data_dir"])
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]
MAP_FILE      = DATA_DIR2 / LOCAL_CONFIG["map_file"]
FASTA         = DATA_DIR2 / LOCAL_CONFIG["fasta"]
SIGNALP_FASTA = WORK_DIR / LOCAL_CONFIG["signalp_fasta"]
SIGNALP_DIR   = WORK_DIR / LOCAL_CONFIG["signalp_dir"]
ORGANISM_TYPE = LOCAL_CONFIG["organism_type"]

rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs.csv"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM.csv"),
        str(SIGNALP_FASTA)

rule add_sequences:
    input:
        nodes = str(DATA_DIR1 / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality.csv"),
        fasta = str(FASTA)
    conda:
        str(WORK_DIR / "env/add-sequence-info.yml")
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        id_mappings   = str(MAP_FILE),
        organism_tag  = ORGANISM_TAG
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-sequence-info.py \
        --nodes         {{input.nodes}} \
        --fasta         {{input.fasta}} \
        --output_prefix {{params.output_prefix}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}} \
        --id_mappings   {{params.id_mappings}}
        """

rule add_DeepTMHMM:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs.csv"),
        preds = str(WORK_DIR / "DeepTMHMM-runs" / f"{ORGANISM_TAG}-results" / f"all-predictions-{ORGANISM_TAG}.3line")
    conda:
        str(WORK_DIR / "env/add-DeepTMHMM-info.yml")
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        organism_tag  = ORGANISM_TAG
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-DeepTMHMM-info.py \
        --nodes         {{input.nodes}} \
        --DeepTMHMM     {{input.preds}} \
        --output_prefix {{params.output_prefix}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}}
        """

rule prepare_SignalP_sequences:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM.csv")
    conda:
        str(WORK_DIR / "env/prepare-SignalP-fasta.yml")
    params:
        output_dir    = str(OUTPUT_DIR),
        organism_tag  = ORGANISM_TAG,
        output_fasta  = SIGNALP_FASTA
    output:
        str(SIGNALP_FASTA)
    shell:
        f"""
        python {WORK_DIR}/python-scripts/prepare-SignalP-fasta.py \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}} \
        --output_fasta  {{params.output_fasta}}
        """
