snakemake -c all --use-conda --conda-frontend conda --snakefile 0-download-inputs/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 1-network-centrality/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 2-sequence-parsing/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 3-uniprot-annotation/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 4-idr-properties/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 5-dG-calculations/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 6-Rosetta-scoring/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 7-protein-half-life/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 8-protein-expression/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 9-translation-efficiency/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 10-predict-PTMs/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 11-entanglement/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 12-chaperones/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 13-oligomers/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 14-domain-annotations/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 15-essentiality/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 16-Y2H-data/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 17-meltome-atlas/Snakefile --configfile config-files/full-rerun-s288c.config
snakemake -c all --use-conda --conda-frontend conda --snakefile 18-finalize/Snakefile --configfile config-files/full-rerun-s288c.config
