from pathlib import Path

LOCAL_CONFIG   = config["LiP_MS"]

INPUT_NODES    = LOCAL_CONFIG["input_nodes"]
DATA_DIR       = Path(config["data_dir"])
WORK_DIR       = Path(workflow.basedir)
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_SUFFIX  = LOCAL_CONFIG["output_suffix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
REFOLDING1_1   = LOCAL_CONFIG["refolding1_1"]
REFOLDING5_1   = LOCAL_CONFIG["refolding5_1"]
REFOLDING120_1 = LOCAL_CONFIG["refolding120_1"]
REFOLDING1_2   = LOCAL_CONFIG["refolding1_2"]
REFOLDING1_2_2 = LOCAL_CONFIG["refolding1_2_2"]
REFOLDING5_2   = LOCAL_CONFIG["refolding5_2"]
REFOLDING5_2_2 = LOCAL_CONFIG["refolding5_2_2"]
REFOLDING120_2 = LOCAL_CONFIG["refolding120_2"]
HEATSHOCK      = LOCAL_CONFIG["heatshock"]
RECOVERY       = LOCAL_CONFIG["recovery"]

rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-refolding.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-heatshock.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-recovery.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"


rule process_refolding:
    input:
        refolding1_1   = str(DATA_DIR / REFOLDING1_1),
        refolding5_1   = str(DATA_DIR / REFOLDING5_1),
        refolding120_1 = str(DATA_DIR / REFOLDING120_1),
        refolding1_2   = str(DATA_DIR / REFOLDING1_2),
        refolding1_2_2 = str(DATA_DIR / REFOLDING1_2_2),        
        refolding5_2   = str(DATA_DIR / REFOLDING5_2),
        refolding5_2_2 = str(DATA_DIR / REFOLDING5_2_2),
        refolding120_2 = str(DATA_DIR / REFOLDING120_2)
    conda:
        "env/process-LiP-MS.yml"
    params:
        output_dir = OUTPUT_DIR,
        organism_tag = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-refolding.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-refolding.py \
        --output_dir     {{params.output_dir}}    \
        --organism_tag   {{params.organism_tag}}  \
        --output_prefix  {{params.output_prefix}} \
        --refolding1_1   {{input.refolding1_1}}   \
        --refolding5_1   {{input.refolding5_1}}   \
        --refolding120_1 {{input.refolding120_1}} \
        --refolding1_2   {{input.refolding1_2}}   \
        --refolding5_2   {{input.refolding5_2}}   \
        --refolding1_2_2 {{input.refolding1_2_2}} \
        --refolding5_2_2 {{input.refolding5_2_2}} \
        --refolding120_2 {{input.refolding120_2}}
        """


rule process_heatshock:
    input:
        heatshock = str(DATA_DIR / HEATSHOCK)
    conda:
        "env/process-LiP-MS.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-heatshock.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-heatshock.py \
        --output_dir    {{params.output_dir}}                 \
        --organism_tag  {{params.organism_tag}}               \
        --output_prefix {{params.output_prefix}}              \
        --heatshock     {{input.heatshock}}
        """


rule process_recovery:
    input:
        recovery = str(DATA_DIR / RECOVERY)
    conda:
        "env/process-LiP-MS.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-recovery.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-recovery.py \
        --output_dir    {{params.output_dir}}                \
        --organism_tag  {{params.organism_tag}}              \
        --output_prefix {{params.output_prefix}}             \
        --recovery      {{input.recovery}}
        """


rule merge_results:
    input:
        refol = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-refolding.csv",
        heats = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-recovery.csv",
        recov = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-processed-heatshock.csv",
        nodes = INPUT_NODES
    conda:
        "env/process-LiP-MS.yml"
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    params:
        output_dir = OUTPUT_DIR,
        organism_tag = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX,
        output_suffix = OUTPUT_SUFFIX
    shell:
        f"""
        python {WORK_DIR}/python-scripts/merge-LiP-MS.py \
        --output_dir      {{params.output_dir}}            \
        --organism_tag    {{params.organism_tag}}          \
        --output_prefix   {{params.output_prefix}}         \
        --output_suffix   {{params.output_suffix}}         \
        --input_nodes     {{input.nodes}}                  \
        --input_refold    {{input.refol}}                  \
        --input_heatshock {{input.heats}}                  \
        --input_recovery  {{input.recov}}
        """
