from pathlib import Path

# read configfile params
LOCAL_CONFIG  = config["network_centrality"]

# define variables
WORK_DIR      = Path(workflow.basedir)
DATA_DIR      = WORK_DIR / config["data_dir"]
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = LOCAL_CONFIG["output_suffix"]
ORGANISM_TAG  = config["organism_label"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
TEST_DIR      = WORK_DIR / LOCAL_CONFIG["test_dir"]
EDGES         = Path(config["data_dir"]) / LOCAL_CONFIG["edges"]
NODES         = Path(config["data_dir"]) / LOCAL_CONFIG["nodes"]
COSDISTPATH   = WORK_DIR / LOCAL_CONFIG["cos_dist_path"]

# overall goal 
rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.csv")

# compute centrality metrics
rule network_centrality:
    input:
        edges = str(EDGES),
        nodes = str(NODES)
    conda:
        str(WORK_DIR / "env/network-analysis.yml")
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        output_suffix = OUTPUT_SUFFIX,
        organism_tag  = ORGANISM_TAG,
        test_dir      = str(TEST_DIR),
        cosdistpath   = str(COSDISTPATH)
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/network-centrality.py \
        --edges         {{input.edges}} \
        --nodes         {{input.nodes}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}} \
        --test_dir      {{params.test_dir}} \
        --CosDistPath   {{params.cosdistpath}}
        """
