from pathlib import Path

LOCAL_CONFIG  = config["dG_predictions"]

WORK_DIR      = Path(workflow.basedir)
DATA_DIR1     = Path(LOCAL_CONFIG["input_dir"])
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]
TEMPERATURE   = LOCAL_CONFIG["temperature"]

rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross-cider-GhoshDill.pkl")

rule ghosh_dill_stability:
    input:
        nodes = str(DATA_DIR1 / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross-cider.pkl")
    conda:
        "env/ghosh-dill-stability.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG,
        temperature    = TEMPERATURE
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross-cider-GhoshDill.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/ghosh-dill-stability.py \
        --nodes                   {{input.nodes}} \
        --output_dir              {{params.output_dir}} \
        --output_prefix           {{params.output_prefix}} \
        --organism_tag            {{params.organism_tag}} \
        --temperature             {{params.temperature}}
        """
