from pathlib import Path

LOCAL_CONFIG   = config["predict_PTMs"]

DATA_DIR       = Path(LOCAL_CONFIG["input_dir"])
WORK_DIR       = Path(workflow.basedir)
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
TOKENIZER_PATH = Path(LOCAL_CONFIG["tokenizer_path"])
MODEL_PATH     = Path(LOCAL_CONFIG["gpt_model_path"])

rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2.pkl",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-PTMGPT2-predictions.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-PTMGPT2-predictions-processed.csv"

rule predict_PTMs:
    input:
        data = f"{DATA_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed.pkl"
    conda:
        "env/ptmgpt2.yml"
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        organism_tag  = ORGANISM_TAG,
        tokenizer     = str(TOKENIZER_PATH),
        model_dir     = str(MODEL_PATH)
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-PTMGPT2-predictions.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/run-PTMGPT2-parallel.py \
        --nodes          {{input.data}} \
        --output_dir     {{params.output_dir}} \
        --output_prefix  {{params.output_prefix}} \
        --organism_tag   {{params.organism_tag}} \
        --tokenizer_path {{params.tokenizer}} \
        --gpt_model_path {{params.model_dir}}
        """

rule process_PTMs:
    input:
        ptms = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-PTMGPT2-predictions.csv",
        nodes = f"{DATA_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed.pkl"
    conda:
        "env/ptmgpt2.yml"
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        organism_tag  = ORGANISM_TAG        
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-PTMGPT2-predictions-processed.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-PTMGPT2.py \
        --input_file    {{input.ptms}} \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}}
        """
