import argparse
from sparrow import Protein
import pandas as pd
from tqdm import tqdm 
from typing import Optional
from typing import Dict 

def run_cider(row: pd.Series) -> Optional[Dict[int, Dict[str, float]]]:

    idr_dict = row.get("IDR_sequences")

    if not isinstance(idr_dict, dict) or not idr_dict:
        return None  # Handle empty or missing dicts

    result = {}

    for idx, seq in idr_dict.items():
        if not seq:
            continue

        try:
            protein = Protein(seq)

            # extract CIDER properties
            cider_props = {
                "Kappa": protein.kappa,
                "Length": len(protein),
                "FCR": protein.FCR,
                "NCPR": protein.NCPR,
                "SHD": protein.SHD,
                "SCD": protein.SCD,
                "Molecular_weight": protein.molecular_weight,
                "F_Neg": protein.fraction_negative,
                "F_Pos": protein.fraction_positive,
                "Hydrophobicity": protein.hydrophobicity,
                "Fraction_aromatic": protein.fraction_aromatic,
                "Fraction_aliphatic": protein.fraction_aliphatic,
                "Fraction_polar": protein.fraction_polar,
                "Complexity": protein.complexity,
            }

            # add amino acid fractions
            for aa, val in protein.amino_acid_fractions.items():
                cider_props[f"Amino_Acid_Fraction_{aa}"] = round(val, 4)

            result[idx] = cider_props

        except Exception as e:
            print(f"Failed to process IDR {idx} in row {row.get('node', '')}: {e}")
            continue

    return result if result else None


def main():

    parser = argparse.ArgumentParser(
        description="Annotate proteins with IDR sequence properties"
    )
    # parser.add_argument("--input_fasta", help="Path to input fasta file")
    parser.add_argument(
        "--nodes",
        help="Path to the node file generated by previous step",
    )
    parser.add_argument("--output_dir", help="Path to output directory")
    parser.add_argument("--output_prefix", help="Prefix to be applied to output file")
    parser.add_argument("--organism_tag", help="Label for the organism for this run")
    args = parser.parse_args()

    # read in the nodes_df from the previous pipeline step
    nodes_df = pd.read_pickle(args.nodes)

    # run cider on all IDR sequences
    tqdm.pandas(desc="Extracting CIDER properties")
    nodes_df["cider"] = nodes_df.progress_apply(run_cider, axis=1)

    # Save updated DataFrame
    nodes_df.to_pickle(
        f"{args.output_dir}/{args.output_prefix}-{args.organism_tag}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross-cider.pkl"
    )

if __name__ == "__main__":

    main()
