from sparrow import Protein
from sparrow.predictors import batch_predict
from Bio import SeqIO
import argparse
import typing
from typing import Optional
from typing import Dict
import pandas as pd
import numpy as np


def run_albatross(row: pd.Series) -> Optional[Dict[int, Dict[str, float]]]:
    """
    Compute IDR ensemble properties

    Args:
        row (pd.Series): a row from a pd.DataFrame containing "IDR_sequences"

    Returns:
        A nested dict or np.nan. Iff dict, keys are integers corresponding to IDR indices and values are dict keyed on property name with properties as values
    """

    idr_dict = row.get("IDR_sequences")

    if not isinstance(idr_dict, dict) or not idr_dict:
        return np.nan  # return np.nan if no IDRs found

    idr_properties = {}

    for idx, seq in idr_dict.items():
        if not seq:
            continue

        properties = {}

        try:
            properties["idr_end_to_end"] = round(
                batch_predict.batch_predict([seq], network="re")[0][1], 3
            )
            properties["idr_end_to_end_scaled"] = round(
                batch_predict.batch_predict([seq], network="scaled_re")[0][1], 3
            )
            properties["idr_rg"] = round(
                batch_predict.batch_predict([seq], network="rg")[0][1], 3
            )
            properties["idr_rg_scaled"] = round(
                batch_predict.batch_predict([seq], network="scaled_rg")[0][1], 3
            )
            properties["idr_asphericity"] = round(
                batch_predict.batch_predict([seq], network="asphericity")[0][1], 3
            )
            properties["idr_scaling_exponent"] = round(
                batch_predict.batch_predict([seq], network="scaling_exponent")[0][1], 3
            )
            properties["idr_prefactor"] = round(
                batch_predict.batch_predict([seq], network="prefactor")[0][1], 3
            )

        except Exception as e:
            print(
                f"Failed to compute IDR properties for IDR {idx} in node {row.get('node')}: {e}"
            )
            continue

        idr_properties[idx] = properties

    return idr_properties if idr_properties else np.nan


def main():

    parser = argparse.ArgumentParser(
        description="Annotate proteins with IDR ensemble properties"
    )
    parser.add_argument(
        "--nodes",
        help="Path to the node file generated by previous pipeline step",
    )
    parser.add_argument("--output_dir", help="Path to output directory")
    parser.add_argument("--output_prefix", help="Prefix to be applied to output file")
    parser.add_argument("--organism_tag", help="Label for the organism for this run")
    args = parser.parse_args()

    # read in the nodes_df generated so far during the pipeline
    nodes_df = pd.read_pickle(args.nodes)

    # run albatross
    nodes_df["albatross"] = nodes_df.apply(run_albatross, axis=1)

    # save the intermediate file
    nodes_df.to_pickle(
        f"{args.output_dir}/{args.output_prefix}-{args.organism_tag}-albatross.pkl"
    )


if __name__ == "__main__":

    main()
