from pathlib import Path

LOCAL_CONFIG  = config["FoldX"]

INPUT_NODES   = Path(LOCAL_CONFIG["input_nodes"])
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = LOCAL_CONFIG["output_suffix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
SCORE_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"] / "scores"
ORGANISM_TAG  = config["organism_label"]
NPROCS        = LOCAL_CONFIG["nprocessors"]
EXEC          = LOCAL_CONFIG["executable"]
STRUCTURE_DIR = LOCAL_CONFIG["structure_dir"]
NSTRUC        = LOCAL_CONFIG["n_structures"]

rule all:
    input:
        str(SCORE_DIR / ".all_foldx_done"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl")

rule run_FoldX:
    input:
        INPUT_NODES
    conda:
        "env/run-FoldX.yml"
    params:
        output_dir     = SCORE_DIR,
        nprocessors    = NPROCS,
        exec           = EXEC,
        struc_dir      = STRUCTURE_DIR,
        nstruc         = NSTRUC
    output:
        str(SCORE_DIR / ".all_foldx_done")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/run-FoldX.py \
        --nodes            {{input}} \
        --output_dir       {{params.output_dir}} \
        --nprocessors      {{params.nprocessors}} \
        --nstruct          {{params.nstruc}} \
        --foldx_executable {{params.exec}} \
        --rosetta_dir      {{params.struc_dir}}
        """

rule add_scores_to_nodes:
    input:
        input_nodes       = INPUT_NODES,
        input_done_signal = str(SCORE_DIR / ".all_foldx_done")
    conda:
        "env/run-FoldX.yml"
    params:
        output_prefix = OUTPUT_PREFIX,
        output_suffix = OUTPUT_SUFFIX,
        input_dir     = SCORE_DIR,
        organism_tag  = ORGANISM_TAG,
        output_dir    = OUTPUT_DIR,
        nstruc        = NSTRUC
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-FoldX-scores.py \
        --nodes         {{input.input_nodes}} \
        --input_dir     {{params.input_dir}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --organism_tag  {{params.organism_tag}} \
        --nstruct       {{params.nstruc}}
        """
