from pathlib import Path

# read configfile information
LOCAL_CONFIG  = config["protein_half_life"]

# define variables
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = LOCAL_CONFIG["output_suffix"]
INPUT_NODES   = LOCAL_CONFIG["input_nodes"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]
HALFLIFE_DB1   = Path(LOCAL_CONFIG["halflife_db1"])
HALFLIFE_DB2   = Path(LOCAL_CONFIG["halflife_db2"])

# overall goal
rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

# integrate half-life data into PPI network
rule add_half_life:
    input:
        INPUT_NODES
    conda:
        "env/add-protein-half-life.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_suffix  = OUTPUT_SUFFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG,
        halflife_db1    = str(HALFLIFE_DB1),
        halflife_db2    = str(HALFLIFE_DB2)
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-half-life.py \
        --nodes         {{input}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --organism_tag  {{params.organism_tag}} \
        --halflife_db1  {{params.halflife_db1}} \
        --halflife_db2  {{params.halflife_db2}}
        """
