from pathlib import Path

# read configfile params
LOCAL_CONFIG  = config["sequence_parsing"]

# define variables
WORK_DIR      = Path(workflow.basedir)
INPUT_NODES   = Path(LOCAL_CONFIG["input_nodes"])
DATA_DIR      = Path(config["data_dir"])
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
OUTPUT_SUFFIX = LOCAL_CONFIG["output_suffix"]
ORGANISM_TAG  = config["organism_label"]
MAP_FILE      = DATA_DIR / LOCAL_CONFIG["map_file"]
FASTA         = DATA_DIR / LOCAL_CONFIG["fasta"]
UNIPROT_FASTA = DATA_DIR / LOCAL_CONFIG["uniprot_fasta"]
SIGNALP_FASTA = OUTPUT_DIR / str(OUTPUT_PREFIX + "-" + ORGANISM_TAG + LOCAL_CONFIG["signalp_fasta_suffix"])
ORGANISM_TYPE = LOCAL_CONFIG["organism_type"]

# overall goal
rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-seqs-{OUTPUT_SUFFIX}.csv"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-DeepTMHMM-{OUTPUT_SUFFIX}.csv"),
        str(SIGNALP_FASTA),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-signalP-prediction-results.txt"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.csv")
        
# add sequence information to nodes
rule add_sequences:
    input:
        nodes = str(INPUT_NODES),
        fasta = str(FASTA),
        uniprot_fasta = str(UNIPROT_FASTA)
    conda:
        str(WORK_DIR / "env/add-sequence-info.yml")
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        output_suffix = OUTPUT_SUFFIX,
        id_mappings   = str(MAP_FILE),
        organism_tag  = ORGANISM_TAG
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-seqs-{OUTPUT_SUFFIX}.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-sequence-info.py \
        --nodes         {{input.nodes}} \
        --fasta         {{input.fasta}} \
        --uniprot_fasta {{input.uniprot_fasta}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}} \
        --id_mappings   {{params.id_mappings}}
        """

# add DeepTMHMM protein classes to nodes
rule add_DeepTMHMM:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-seqs-{OUTPUT_SUFFIX}.csv"),
        preds = str(WORK_DIR / "DeepTMHMM-runs" / f"{ORGANISM_TAG}-results" / f"all-predictions-{ORGANISM_TAG}.3line")
    conda:
        str(WORK_DIR / "env/add-DeepTMHMM-info.yml")
    params:
        output_prefix = OUTPUT_PREFIX,
        output_dir    = str(OUTPUT_DIR),
        output_suffix = OUTPUT_SUFFIX,
        organism_tag  = ORGANISM_TAG
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-DeepTMHMM-{OUTPUT_SUFFIX}.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-DeepTMHMM-info.py \
        --nodes         {{input.nodes}} \
        --DeepTMHMM     {{input.preds}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}}
        """

# prepare sequences in format required by SignalP
rule prepare_SignalP_sequences:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-DeepTMHMM-{OUTPUT_SUFFIX}.csv")
    conda:
        str(WORK_DIR / "env/prepare-SignalP-fasta.yml")
    params:
        output_dir    = str(OUTPUT_DIR / "signalP"),
        organism_tag  = ORGANISM_TAG,
        output_fasta  = SIGNALP_FASTA
    output:
        str(SIGNALP_FASTA)
    shell:
        f"""
        python {WORK_DIR}/python-scripts/prepare-SignalP-fasta.py \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --organism_tag  {{params.organism_tag}} \
        --output_fasta  {{params.output_fasta}}
        """

# run SignalP
rule run_SignalP:
    input:
        fasta = str(SIGNALP_FASTA)
    conda:
        str(WORK_DIR / "env/signalp-fast-local.yml")
    params:
        organism_type = ORGANISM_TYPE,
        output_dir1   = str(OUTPUT_DIR / "signalP"),
        output_dir2   = str(OUTPUT_DIR), 
        output_format = "txt",
        run_mode      = "fast"
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-signalP-prediction-results.txt")
    shell:
        f"""
        signalp6 --fastafile {{input.fasta}} --organism {ORGANISM_TYPE} --output_dir {{params.output_dir1}} --format {{params.output_format}} --mode {{params.run_mode}}
        mv {{params.output_dir1}}/prediction_results.txt {{params.output_dir2}}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-signalP-prediction-results.txt
        rm -r {{params.output_dir1}}
        """

# generate final annotated nodes file for this step with SignalP trimmed sequences
rule SignalP_trim:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-signalP-prediction-results.txt")
    conda:
        str(WORK_DIR / "env/signalp-trim.yml")
    params:
        nodes         = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-DeepTMHMM-{OUTPUT_SUFFIX}.csv"),
        output_dir    = str(OUTPUT_DIR),
        output_suffix = OUTPUT_SUFFIX,
        output_prefix = OUTPUT_PREFIX,
        organism_tag  = ORGANISM_TAG,
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/parse-sequences-by-SignalP-output.py \
        --nodes               {{params.nodes}} \
        --output_dir          {{params.output_dir}} \
        --output_prefix       {{params.output_prefix}} \
        --organism_tag        {{params.organism_tag}} \
        --signalP_predictions {{input}} \
        --output_suffix       {{params.output_suffix}}
        """
