from pathlib import Path

LOCAL_CONFIG  = config["protein_expression"]

INPUT_NODES   = Path(LOCAL_CONFIG["input_nodes"])
OUTPUT_SUFFIX = LOCAL_CONFIG["output_suffix"]
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]
EXPRESSION_DB = Path(LOCAL_CONFIG["expression_db"])

rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

rule add_expression:
    input:
        INPUT_NODES
    conda:
        "env/add-protein-expression.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_suffix  = OUTPUT_SUFFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG,
        expression_db  = str(EXPRESSION_DB)
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-expression.py \
        --nodes         {{input}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --organism_tag  {{params.organism_tag}} \
        --expression_db {{params.expression_db}}
        """
