from pathlib import Path

LOCAL_CONFIG  = config["flatten_nodes"]

INPUT_NODES   = LOCAL_CONFIG["input_nodes"]
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = config["output_suffix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]

rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.csv"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-per-IDR-{OUTPUT_SUFFIX}.csv"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-per-IDR-{OUTPUT_SUFFIX}.pkl")

rule flatten_nodes:
    input:
        INPUT_NODES
    conda:
        "env/flatten.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_suffix  = OUTPUT_SUFFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG 
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.csv"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-per-IDR-{OUTPUT_SUFFIX}.csv"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-per-IDR-{OUTPUT_SUFFIX}.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/flatten.py \
        --nodes         {{input}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}}
        """
