from pathlib import Path

LOCAL_CONFIG  = config["flatten_nodes"]
PREV_CONFIG   = config["dG_predictions"]

DATA_DIR      = Path(LOCAL_CONFIG["input_dir"])
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
FINAL_PREFIX  = LOCAL_CONFIG["final_prefix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]

rule all:
    input:
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-node.csv"),
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-node.pkl"),
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-IDR.csv"),
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-IDR.pkl")

rule flatten_nodes:
    input:
        f"{DATA_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2-LiPMS-entanglement.pkl"
        #f"{DATA_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-speed-PTMGPT2-LiPMS.pkl"
        #f"{DATA_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-SignalP-UniProt-IDRs-albatross-cider-GhoshDill-Cagiada-Rosetta-FoldX-halflife-expr-PTMGPT2.pkl"
    conda:
        "env/flatten.yml"
    params:
        output_prefix  = FINAL_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG 
    output:
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-node.csv"),
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-node.pkl"),
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-IDR.csv"),
        str(OUTPUT_DIR / f"{FINAL_PREFIX}-{ORGANISM_TAG}-nodes-final-per-IDR.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/flatten.py \
        --nodes         {{input}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}}
        """
