from pathlib import Path

LOCAL_CONFIG  = config["idr_properties"]

WORK_DIR       = Path(workflow.basedir)
DATA_DIR1      = Path(LOCAL_CONFIG["input_dir"])
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
MIN_IDR_LENGTH = LOCAL_CONFIG["min_idr_length"]
DISORDER_RESI  = LOCAL_CONFIG["disorder_resi_cut"]
DISORDER_PROT  = LOCAL_CONFIG["disorder_prot_cut"]
SEQ_COLUMN     = LOCAL_CONFIG["seq_column"] 

rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs.pkl"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross.pkl"),
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross-cider.pkl")

rule predict_IDRs:
    input:
        nodes = str(DATA_DIR1 / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt.csv")
    conda:
        "env/metapredict.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG,
        min_idr_length = MIN_IDR_LENGTH,
        disorder_aa    = DISORDER_RESI,
        disorder_prot  = DISORDER_PROT,
        seq_column     = SEQ_COLUMN
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-idr-predictions.py \
        --nodes                   {{input.nodes}} \
        --output_dir              {{params.output_dir}} \
        --output_prefix           {{params.output_prefix}} \
        --organism_tag            {{params.organism_tag}} \
        --min_idr_length          {{params.min_idr_length}} \
        --disorder_threshold_aa   {{params.disorder_aa}} \
        --disorder_threshold_prot {{params.disorder_prot}} \
        --seq_column_to_use       {{params.seq_column}}
        """

rule run_albatross:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs.pkl")
    conda:
        "env/albatross.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/run-albatross.py \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}}
        """

rule run_cider:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross.pkl")
    conda:
        "env/cider.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-nodes-centrality-seqs-DeepTMHMM-UniProt-IDRs-albatross-cider.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/run-cider.py \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}}
        """
