from pathlib import Path

# read config file params
LOCAL_CONFIG      = config["download_inputs"]
WORK_DIR          = Path(workflow.basedir)
DATA_DIR          = Path(config["data_dir"]).resolve()
SCRIPTS_DIR       = WORK_DIR / "bash-scripts"
EXTRACTSEQ_SCRIPT = SCRIPTS_DIR / "extract-seqres.sh"
UNPACK_SCRIPT     = SCRIPTS_DIR / "unpack-files.sh"
GOCMD             = Path(LOCAL_CONFIG["gocommands"])
CYVERSE_DIR       = Path(LOCAL_CONFIG["cyverse_directory"])

rule all:
    input:
        str(DATA_DIR / ".all_files_downloaded"),
        str(DATA_DIR / ".all_files_unpacked"),
        str(DATA_DIR / ".all_fasta_created")

# download data from CyVerse with gocommands
rule download_inputs:
    input: []
    params:
        gocmd       = GOCMD,
        cyverse_dir = CYVERSE_DIR,
        output_dir  = WORK_DIR
    output:
        str(DATA_DIR / ".all_files_downloaded")
    shell:
        "{params.gocmd} get --progress {params.cyverse_dir} {params.output_dir} && touch {output}"

# unpack compressed/archived files
rule unpack_files:
    input:
        str(DATA_DIR / ".all_files_downloaded")
    params:
        output_dir = DATA_DIR,
        script     = UNPACK_SCRIPT
    output:
        str(DATA_DIR / ".all_files_unpacked")
    shell:
        "bash {params.script} {params.output_dir} && touch {output}"

# extract fasta sequences from PDB files
rule create_fasta:
    input:
        str(DATA_DIR / ".all_files_unpacked")
    output:
        str(DATA_DIR / ".all_fasta_created")
    params:
        script     = str(EXTRACTSEQ_SCRIPT),
        target_dir = str(DATA_DIR)
    shell:
        "bash {params.script} {params.target_dir}"
