from pathlib import Path

# read configfile params
LOCAL_CONFIG  = config["dG_predictions"]

# define variables
WORK_DIR      = Path(workflow.basedir)
INPUT_NODES   = LOCAL_CONFIG["input_nodes"]
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = LOCAL_CONFIG["output_suffix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]
TEMPERATURE   = LOCAL_CONFIG["temperature"]
STRUCTURE_DIR = Path(LOCAL_CONFIG["structure_dir"])
ESM_MODEL     = Path(LOCAL_CONFIG["ESM_model"])
SEQ_COLUMN    = LOCAL_CONFIG["seq_column"]
TEST_DIR      = WORK_DIR / LOCAL_CONFIG["test_dir"]
AF2_DIR       = LOCAL_CONFIG["AF2_dir"]

# overall goal
rule all:
    input:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl")

# finalize structure selection for dG calculations
rule prepare_structures:
    input:
        nodes = INPUT_NODES
    conda:
        "env/prepare-structures.yml"
    params:
        input_dir     = str(STRUCTURE_DIR),
        output_dir    = str(OUTPUT_DIR),
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX,
        AF2_dir       = AF2_DIR
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-temp.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/prepare-structures.py \
        --nodes         {{input.nodes}} \
        --input_dir     {{params.input_dir}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}} \
        --AF2_dir       {{params.AF2_dir}} \
        > {WORK_DIR}/prepare-structures.log
        """

# predict dG with Ghosh-Dill equation
rule ghosh_dill_stability:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-temp.pkl")
    conda:
        "env/ghosh-dill-stability.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG,
        temperature    = TEMPERATURE,
        seq_column     = SEQ_COLUMN
    output:
        nodes          = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-GhoshDill.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/ghosh-dill-stability.py \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --organism_tag  {{params.organism_tag}} \
        --temperature   {{params.temperature}} \
        --seq_column_to_use {{params.seq_column}}
        """

# predict |dG| with Cagiada et al. 2025 model
rule cagiada_stability:
    input:
        nodes          = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-GhoshDill.pkl")
    conda:
        "env/cagiada-stability.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG,
        structure_dir  = STRUCTURE_DIR,
        ESM_model      = ESM_MODEL,
        test_dir       = TEST_DIR
    output:
        csv = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-cagiada-dG.csv")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/cagiada-stability.py \
        --nodes          {{input.nodes}} \
        --output_dir     {{params.output_dir}} \
        --output_prefix  {{params.output_prefix}} \
        --organism_tag   {{params.organism_tag}} \
        --structure_dir  {{params.structure_dir}} \
        --ESM_model      {{params.ESM_model}} \
        --test_dir       {{params.test_dir}} \
        > {WORK_DIR}/cagiada.log
        """

# merge Cagiada et al. 2025 results with nodes_df
rule merge_cagiada_with_nodes:
    input:
        nodes = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-GhoshDill.pkl"),
        cagiada = str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-cagiada-dG.csv")
    conda:
        "env/cagiada-stability.yml"
    output:
        str(OUTPUT_DIR / f"{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl")
    shell:
        f"""
        python {WORK_DIR}/python-scripts/merge-cagiada.py \
        --nodes   {{input.nodes}} \
        --cagiada {{input.cagiada}} \
        --output  {{output}}
        """
