from pathlib import Path

LOCAL_CONFIG  = config["meltome"]

INPUT_NODES   = LOCAL_CONFIG["input_nodes"]
DATA_DIR      = Path(config["data_dir"])
WORK_DIR      = Path(workflow.basedir)
OUTPUT_PREFIX = config["output_prefix"]
OUTPUT_SUFFIX = config["output_suffix"]
OUTPUT_DIR    = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG  = config["organism_label"]
MELTOME_DATA  = DATA_DIR / LOCAL_CONFIG["meltome_data"]

rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

rule add_meltome:
    input:
        meltome = str(MELTOME_DATA),
        nodes = INPUT_NODES
    conda:
        "env/merge-meltome.yml"
    params:
        output_dir      = OUTPUT_DIR,
        output_prefix   = OUTPUT_PREFIX,
        output_suffix   = OUTPUT_SUFFIX,
        organism_tag    = ORGANISM_TAG
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/merge-meltome.py \
        --nodes         {{input.nodes}} \
        --output_dir    {{params.output_dir}} \
        --output_prefix {{params.output_prefix}} \
        --output_suffix {{params.output_suffix}} \
        --organism_tag  {{params.organism_tag}} \
        --meltome_data  {{input.meltome}}
        """
