from pathlib import Path

# read configfile params
LOCAL_CONFIG   = config["domain_annotations"]

# define variables
INPUT_NODES    = LOCAL_CONFIG["input_nodes"]
DATA_DIR       = Path(config["data_dir"])
WORK_DIR       = Path(workflow.basedir)
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_SUFFIX  = LOCAL_CONFIG["output_suffix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
DOMAIN_DATA    = DATA_DIR / LOCAL_CONFIG["annotations"]

# overall goal
rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

# parse InterPro database to extract annotations for organism of interest
rule extract_domain_info:
    input:
        nodes = INPUT_NODES
    conda:
        "env/domains.yml"
    params:
        output_dir    = OUTPUT_DIR,  
        organism_tag  = ORGANISM_TAG, 
        output_prefix = OUTPUT_PREFIX,
        domain_data   = str(DOMAIN_DATA)
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations.csv"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/extract-InterPro.py \
        --output_dir     {{params.output_dir}}               \
        --output_prefix  {{params.output_prefix}}            \
        --organism_tag   {{params.organism_tag}}             \
        --domain_data    {{params.domain_data}}              \
        --nodes          {{input.nodes}}
        """

# post-process extracted information into usable format
rule process_domain_info:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations.csv"
    conda:
        "env/domains.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.csv",
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/process-InterPro.py \
        --output_dir     {{params.output_dir}}               \
        --output_prefix  {{params.output_prefix}}            \
        --organism_tag   {{params.organism_tag}}             \
        --input_data     {{input}}
        """

# integrate into nodes_df (annotated PPI network)
rule add_domain_info:
    input:
        nodes = INPUT_NODES,
        info  = f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-domain-annotations-processed.pkl"
    conda:
        "env/domains.yml"
    params:
        output_dir    = OUTPUT_DIR,
        organism_tag  = ORGANISM_TAG,
        output_prefix = OUTPUT_PREFIX,
        output_suffix = OUTPUT_SUFFIX
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-InterPro.py \
        --output_dir     {{params.output_dir}}           \
        --output_prefix  {{params.output_prefix}}        \
        --output_suffix  {{params.output_suffix}}        \
        --organism_tag   {{params.organism_tag}}         \
        --domain_data    {{input.info}}                  \
        --input_nodes    {{input.nodes}}
        """
