from pathlib import Path

LOCAL_CONFIG   = config["translation_speed"]

INPUT_NODES    = LOCAL_CONFIG["input_nodes"]
WORK_DIR       = Path(workflow.basedir)
OUTPUT_PREFIX  = config["output_prefix"]
OUTPUT_SUFFIX  = LOCAL_CONFIG["output_suffix"]
OUTPUT_DIR     = WORK_DIR / LOCAL_CONFIG["output_dir"]
ORGANISM_TAG   = config["organism_label"]
RAW_DATA_DIR   = Path(LOCAL_CONFIG["raw_data_dir"])
DATA_FILE      = RAW_DATA_DIR / LOCAL_CONFIG["data_file"]

rule all:
    input:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"

rule add_translation_efficiency:
    input:
        nodes = INPUT_NODES,
        data  = DATA_FILE
    conda:
        "env/add-translation-speed.yml"
    params:
        output_prefix  = OUTPUT_PREFIX,
        output_suffix  = OUTPUT_SUFFIX,
        output_dir     = str(OUTPUT_DIR),
        organism_tag   = ORGANISM_TAG
    output:
        f"{OUTPUT_DIR}/{OUTPUT_PREFIX}-{ORGANISM_TAG}-{OUTPUT_SUFFIX}.pkl"
    shell:
        f"""
        python {WORK_DIR}/python-scripts/add-translation-speed.py \
        --nodes            {{input.nodes}} \
        --output_dir       {{params.output_dir}} \
        --output_prefix    {{params.output_prefix}} \
        --output_suffix    {{params.output_suffix}} \
        --organism_tag     {{params.organism_tag}} \
        --input_file       {{input.data}}
        """
